---
title: "DESeq2_plots.epidermal"
author: "zhu"
date: "2017年5月4日"
output: html_notebook

---
```{r}
library(ggplot2)
library(reshape2)
setwd("~/R/epider")
load(".RData")
```


```{r constantly plot}
#

#constant_up <- read.table("constantly_up.txt",header = T,sep = "\t")

test <- rbind(constant_up[which(constant_up$res3_change=="NOT"),c(1,2,5,8)],constant_down[which(constant_down$res3_change=="NOT"),c(1,2,5,8)])
test1 <- melt(test)
test2 <- test1[order(test1$Row.names),]
test2$x <- rep(1:3,length(rownames(test2))/3)

data <- read.table("/home/qszhu/workspace/2.nmyc/7.plotHeatmap/ann/fimo_all_Nmyc_motif.bed",header = F,quote = "",sep = "\t")

p1 <-ggplot(data = test2) + geom_line(aes(x=x,y=value,group=Row.names)) + theme(plot.subtitle = element_text(vjust = 1), 
    plot.caption = element_text(vjust = 1), 
    axis.line = element_line(linetype = "solid"), 
    panel.background = element_rect(fill = "green2"), 
    plot.background = element_rect(fill = "antiquewhite"))
ggplot(data = data2, aes(x = control)) +
geom_histogram(aes(y = ..density..), bins = 10) +
theme_bw() +
geom_density(fill = 'firebrick', alpha = 0.5)

ggExtra::ggMarginal(
  p = p1,
  type = 'histogram',
  margins = 'both',
  size = 4.5,
  col = '#ED2121',
  fill = '#2D48E0'
)


print(g)

data2

```

```{r heatmap for select genes}
temp <- read.table("chart_KEGG_down.txt",header = F,sep = "\t",row.names = NULL)
select <- strsplit(as.vector(temp[2,6]),split=", ")[[1]]
#temp <- temp[!duplicated(temp$V1),]
data <- res_merge
rownames(data) <- data$Row.names
data <- data[,-1]

#select <- as.vector(temp[,1])
data <- data[select,c(1,4,7)]
colnames(data) <- c("log2FC(0d)","log2FC(90d)","log2FC(120d)")
colnames(data) <- c("0d","90d","120d")
pheatmap(data, cluster_rows=T, show_rownames=T,cluster_cols=F,filename = "PI3K_FC_heatmap.pdf")


```

```{r gene heatmap}
#select <- row.names(res_frame[order(res_frame$log2FoldChange),])[1:20]
#select <- row.names(res_frame[which(res_frame$change=="DOWN"),])
#select <- row.names(res_frame[which(res_frame$change=="UP"),])
nt <- normTransform(dds) # defaults to log2(x+1)
log2.norm.counts <- assay(nt)[select,]
dds$treated = Treated
df <- as.data.frame(colData(dds)[,c("treated")])
pheatmap(log2.norm.counts, cluster_rows=T, show_rownames=T,cluster_cols=T)
pheatmap(assay(rld)[select,], cluster_rows=T, show_rownames=T,cluster_cols=F,filename = "PI3K_rld_heatmap.pdf")
```

```{r rld treated means heatmap}
#rld <- rlog(dds, blind=TRUE)
data <- assay(rld)[select,]

data2 <- data.frame("0d"=rowMeans(data[,colData(dds)$treated=="case1"]),
                   "90d"=rowMeans(data[,colData(dds)$treated=="case2"]),
                    "120d"=rowMeans(data[,colData(dds)$treated=="case3"]),
                    control=rowMeans(data[,colData(dds)$treated=="control"]),check.names = F
                    )

pheatmap(data2, cluster_rows=T, show_rownames=T,cluster_cols=F,cellwidth = 20,cellheight = 10,filename = "PI3K_rld_heatmap_down1.pdf")



```



```{r }
temp <- read.table("go_term/constantly_up_DOWN.txt",header = F,sep = "\t",row.names = NULL)
select1 <- strsplit(as.vector(temp[2,6]),split=", ")[[1]]
select2 <- strsplit(as.vector(temp[3,6]),split=", ")[[1]]
select3 <- strsplit(as.vector(temp[6,6]),split=", ")[[1]]
select <- c(select1,select2,select3)
select <- select[!duplicated(select)]


data <- assay(rld)[select,]
data2 <- data.frame("0d"=rowMeans(data[,colData(dds)$treated=="case1"]),
                   "90d"=rowMeans(data[,colData(dds)$treated=="case2"]),
                    "120d"=rowMeans(data[,colData(dds)$treated=="case3"]),
                    control=rowMeans(data[,colData(dds)$treated=="control"]),check.names = F
                    )

pheatmap(data2, cluster_rows=T, show_rownames=T,cluster_cols=F,cellwidth = 20,cellheight = 10,filename = "keratinization_rld_heatmap_up1.pdf")


```




```{r}
counts(dds,normalized = T)
```

